version: '1'

services:
  nginx:
    image: docker.io/nginx
    ports:
      - 127.0.0.1:8080:80 

    volumes:
      - ./app:/usr/share/nginx/html:rw
      - ./.docker/nginx:/etc/nginx/conf.d:ro
      - ./.docker/log/nginx:/var/log/nginx
      
    restart: always

  php:
    # image: docker.io/php
    build: .docker/php
    working_dir: /var/www/html
    volumes:
      - ./app:/usr/share/nginx/html:rw
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini:rw
    depends_on:
      - nginx
      - postgresql
    restart: always

  postgresql:
    image: docker.io/postgres
    ports:
      - 127.0.0.1:6543:5432 # PostgreSQL
    volumes:
      - postgresqldata:/var/lib/postgresql/data
      - ./.docker/log/postgresql:/var/log/postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    restart: always




volumes:
  postgresqldata: 
