version: '1'

services:
  nginx:
    image: docker.io/nginx
    ports:
      # If you want to change the used port, modify the first one
      # If you want to connect from other devices on the same network, remove the two
      - 127.0.0.1:8080:80 # Nginx+Php server

    volumes:
      - ./app:/usr/share/nginx/html:rw
      - ./.docker/nginx:/etc/nginx/conf.d:ro
      # - ./config/nginx:/etc/nginx/conf.d:rw
      - ./.docker/log/nginx:/var/log/nginx
      
    restart: always

  php:
    # image: docker.io/php
    build: .docker/php
    working_dir: /var/www/html
    volumes:
      - ./app:/usr/share/nginx/html:rw
      # - ./config/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini:rw
    depends_on:
      - nginx
      - postgresql
      # - mariadb
    restart: always

  postgresql:
    image: docker.io/postgres
    ports:
      - 127.0.0.1:6543:5432 # PostgreSQL
    volumes:
      - postgresqldata:/var/lib/postgresql/data
      - ./.docker/log/postgresql:/var/log/postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    restart: always




volumes:
  postgresqldata: 
  # mariadbdata:


  # mariadb:
  #   image: docker.io/mariadb 
  #   ports:
  #     - 127.0.0.1:8081:3306 # MariaDB
  #   volumes:
  #     - mariadbdata:/var/lib/mysql:rw
  #     - ./log/mariadb:/var/log/mysql
  #   environment:
  #     MARIADB_ROOT_PASSWORD: root
  #     MARIADB_USER: user
  #     MARIADB_PASSWORD: password
  #   restart: always

# version: "3"

# services:
#   nginx:
#     image: docker.io/nginx:alpine
#     ports:
#       # If you want to change the used port, modify the first one
#       # If you want to connect from other devices on the same network, remove the two 127.0.0.1:
#       - 127.0.0.1:9090:80 # Nginx+Php server
#       - 127.0.0.1:9091:8080 # Phpmyadmin
#     volumes:
#       - ./app:/var/www/html:rw
#       - ./config/nginx:/etc/nginx/conf.d:rw
#       - ./log/nginx:/var/log/nginx
#       - phpmyadmindata:/var/www/phpmyadmin:rw
#     restart: always

#   php:
    # build:
    #   context: .
    #   dockerfile: php-dockerfile # PHP FPM
    # working_dir: /var/www/html
#     volumes:
#       - ./app:/var/www/html:rw
#       - ./config/php/php.ini:/usr/local/etc/php/php.ini:rw
#     depends_on:
#       - nginx
#       - mariadb
#     restart: always

#   mariadb:
#     # Use this image instead of the official one
#     #image: monstrenyatko/rpi-mariadb # RPI image
#     image: docker.io/mariadb # Official image
#     volumes:
#       - mariadbdata:/var/lib/mysql:rw
#       - ./log/mariadb:/var/log/mariadb
#     environment:
#       MARIADB_ROOT_PASSWORD: root
#       # MARIADB_USER: user
#       # MARIADB_PASSWORD: password
#     restart: always

#   phpmyadmin:
#     image: docker.io/phpmyadmin:fpm-alpine
#     volumes:
#       - phpmyadmindata:/var/www/html:rw
#     environment:
#       PMA_HOST: mariadb
#       PMA_USER: root
#       PMA_PASSWORD: root
#       #PMA_USER: user
#       #PMA_PASSWORD: password
#     depends_on:
#       - mariadb
#     restart: always

#   node:
#     image: docker.io/node:alpine
#     working_dir: /var/node/app
#     volumes:
#       - ./app:/var/node/app
#     #command: sh -c "npm install && tail -f /dev/null"
#     restart: always

# volumes:
#   mariadbdata:
#   phpmyadmindata:
